# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mazmorreo en solitario
email: mazmorreoensolitario@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mazmorreo en Solitario es un blog sobre juegos de mesa para un jugador.
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mazmorreoensolitario.github.io" # the base hostname & protocol for your site

#sidebar
# If there is no featured image in a post then this image will be showed.
# Also on all pages this image will be showed. Use a 500x250 image.
default-image: logo.png 

#footer

built-by: 

copyright:
   name: Mazmorreo en solitario
   link: 'https://mazmorreoensolitario.github.io'

default_locale: "es"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 12
paginate_path: /page:num/

# Comments
disqus: no
#disqus-shortname: webjeda-demo

# social
twitter: http://twitter.com/mazmorreo
email: mazmorreoensolitario@gmail.com

# analytics
analytics: UA-130120400-1

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

